package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.util.Duration;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.animation.KeyFrame;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.scene.control.Alert;
import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MainSceneController implements Initializable {
	@FXML
	private Text parisTickets;
//	private Text londonTickets;
//	private Text newyorkTickets;
	@FXML

	private TextField ticketNo;

	// Event Listener on Button.onAction
	@FXML
	public void submitBtn(ActionEvent event) {
		// TODO Autogenerated

		Platform.runLater(() -> {

			try {
				Book book = new Book();
				Reader read = new Reader();

				if (read.getParis() == 0) {
					throw new IllegalArgumentException("No tickets reamaining");
				}

				Thread thread = new Thread(book);
				thread.start();
				thread.join();
				book.book(Integer.parseInt(ticketNo.getText()));

				Alert alert = new Alert(Alert.AlertType.INFORMATION);
				alert.setTitle("SUCCESS");
				alert.setContentText("Ticket booked successfully");
				Stage stage = (Stage) alert.getDialogPane().getScene().getWindow();
				stage.getIcons().add(new Image("C:\\Users\\yhya2\\Desktop\\Hamid\\images\\check.png"));
				alert.showAndWait();

			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();

			} catch (NumberFormatException e) {
				// TODO Auto-generated catch block
				Alert alert = new Alert(Alert.AlertType.WARNING);
				alert.setTitle("WARNING");
				alert.setContentText("Please enter a valid number");
				Stage stage = (Stage) alert.getDialogPane().getScene().getWindow();
				stage.getIcons().add(new Image("C:\\Users\\yhya2\\Desktop\\Hamid\\images\\warning.png"));
				alert.showAndWait();

			} catch (IllegalArgumentException e) {
				Alert alert = new Alert(Alert.AlertType.WARNING);
				alert.setTitle("WARNING");
				alert.setContentText("No tickets available");
				Stage stage = (Stage) alert.getDialogPane().getScene().getWindow();
				stage.getIcons().add(new Image("C:\\Users\\yhya2\\Desktop\\Hamid\\images\\warning.png"));
				alert.showAndWait();
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		});
	}

	// Event Listener on Button.onAction
	@FXML
	public void removeBtn(ActionEvent event) {
		try {
			if (ticketNo.getText() == "") {
				throw new IllegalArgumentException("Text feild is empty");

			}
			Remove remove = new Remove();
			UnBook unbook = new UnBook();
			remove.run(ticketNo.getText());
			unbook.run();

			Alert alert = new Alert(Alert.AlertType.INFORMATION);
			alert.setTitle("SUCCESS");
			alert.setContentText("Ticket removed successfully");
			Stage stage = (Stage) alert.getDialogPane().getScene().getWindow();
			stage.getIcons().add(new Image("C:\\Users\\yhya2\\Desktop\\Hamid\\images\\check.png"));
			alert.showAndWait();

		} catch (IllegalArgumentException e) {

			Alert alert = new Alert(Alert.AlertType.WARNING);
			alert.setTitle("WARNING");
			alert.setContentText("Please enter a ticket number to be removed");
			Stage stage = (Stage) alert.getDialogPane().getScene().getWindow();
			stage.getIcons().add(new Image("C:\\Users\\yhya2\\Desktop\\Hamid\\images\\warning.png"));
			alert.showAndWait();

		} catch (Exception e) {

			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setTitle("FAILED");
			alert.setContentText("Ticket was not removed successfully due to an Error occured");
			Stage stage = (Stage) alert.getDialogPane().getScene().getWindow();
			stage.getIcons().add(new Image("C:\\Users\\yhya2\\Desktop\\Hamid\\images\\cancel.png"));
			alert.showAndWait();

		}

	}

	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		new Thread() {
			public void run() {
				try {
					while (true) {
						Reader read = new Reader();
						Thread tickets = new Thread(read);
						tickets.start();
						tickets.join();

						parisTickets.setText(Integer.toString(read.getParis()));

						Thread.sleep(100);
					}
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}

		}.start();
	}
}
