package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.text.Text;
import javafx.util.Duration;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.animation.KeyFrame;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MainSceneController implements Initializable {
	@FXML
	private Text parisTickets;
//	private Text londonTickets;
//	private Text newyorkTickets;
	@FXML

	private TextField ticketNo;

	// Event Listener on Button.onAction
	@FXML
	public void submitBtn(ActionEvent event) {
		// TODO Autogenerated
		Platform.runLater(() -> {

			try {
				Book book = new Book();
				Thread thread = new Thread(book);
				thread.start();
				thread.join();
				book.book(Integer.parseInt(ticketNo.getText()));
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (NumberFormatException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		});
	}

	// Event Listener on Button.onAction
	@FXML
	public void removeBtn(ActionEvent event) {
		Remove remove = new Remove();
		UnBook unbook = new UnBook();
		
		unbook.run();
		remove.run(ticketNo.getText());;
	}

	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		new Thread() {
			public void run() {
				try {
					while (true) {
						Reader read = new Reader();
						Thread tickets = new Thread(read);
						tickets.start();
						tickets.join();

						parisTickets.setText(Integer.toString(read.getParis()));

						Thread.sleep(100);
					}
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}

		}.start();
	}
}
